name: Symlink

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
     - name: clone
       run: |
         ln -s ./page/ ./
     - name: show
       run: |
         ls -a -R
